openapi: 3.0.3
info:
  title: 'todo list'
  description: 'todo list'
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: auth.failed
                  errors:
                    account:
                      - auth.failed
                properties:
                  message:
                    type: string
                    example: auth.failed
                  errors:
                    type: object
                    properties:
                      account:
                        type: array
                        example:
                          - auth.failed
                        items:
                          type: string
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: string
                  description: ''
                  example: vel
                password:
                  type: string
                  description: ''
                  example: reprehenderit
              required:
                - account
                - password
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Endpoints
      security: []
  /api/member:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    name: 帥依庭
                    group: UI/UX
                    created_at: '2023-08-21T04:04:35.000000Z'
                    updated_at: '2023-08-21T04:04:35.000000Z'
                    tasks:
                      -
                        id: 16
                        task_descr: 'Et nihil veritatis qui minus provident sed. Cupiditate explicabo quia qui deleniti.'
                        member_id: '1'
                        creator_id: '11'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 25
                        task_descr: 'Quia eligendi labore sed dolor nihil. Reprehenderit est repellat magni necessitatibus. Nulla molestiae sed minima quas. Modi ipsum est aut modi.'
                        member_id: '1'
                        creator_id: '4'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 42
                        task_descr: 'Repellendus aperiam repellat repellendus reprehenderit quis eum. Quia voluptas dolore assumenda corrupti sequi impedit tenetur. Ad hic voluptatem aut consequuntur et ut et.'
                        member_id: '1'
                        creator_id: '9'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                      -
                        id: 50
                        task_descr: 'Et praesentium distinctio deleniti culpa. Deserunt tempore et non veritatis et. Exercitationem beatae in aut molestiae quam.'
                        member_id: '1'
                        creator_id: '9'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                  -
                    id: 2
                    name: 嚴霖廷
                    group: Back-end
                    created_at: '2023-08-21T04:04:35.000000Z'
                    updated_at: '2023-08-21T04:04:35.000000Z'
                    tasks:
                      -
                        id: 5
                        task_descr: 'Eos sint praesentium voluptatem expedita ut molestiae quos. Voluptatem ea asperiores et enim cum et.'
                        member_id: '2'
                        creator_id: '2'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 8
                        task_descr: 'Sit sint fugiat ipsum deleniti. Repudiandae eveniet nulla aut et quia odit reiciendis. Esse voluptatem voluptates non reprehenderit et. Aliquid et eum ut cumque et.'
                        member_id: '2'
                        creator_id: '9'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 47
                        task_descr: 'Voluptate voluptatem molestiae quis quia. Veniam rerum et est et. Similique sit aut ut tempore.'
                        member_id: '2'
                        creator_id: '11'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                      -
                        id: 48
                        task_descr: 'set ap'
                        member_id: '2'
                        creator_id: '1'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-22 01:55:23'
                  -
                    id: 3
                    name: 鄂銘彥
                    group: Front-end
                    created_at: '2023-08-21T04:04:35.000000Z'
                    updated_at: '2023-08-21T04:04:35.000000Z'
                    tasks:
                      -
                        id: 35
                        task_descr: 'Perferendis quasi eos eos voluptatibus et et. Et aut praesentium maiores.'
                        member_id: '3'
                        creator_id: '11'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                      -
                        id: 37
                        task_descr: 'Veniam sapiente asperiores at perferendis ipsam omnis quibusdam. Unde aliquam minus quod ipsa deleniti dicta. Sint mollitia quis cum consequatur.'
                        member_id: '3'
                        creator_id: '4'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                      -
                        id: 38
                        task_descr: 'Aut dolores consequuntur quaerat sequi. Aut vero natus similique quasi amet consectetur. Accusamus voluptatum autem ratione similique molestiae voluptatum modi.'
                        member_id: '3'
                        creator_id: '11'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                  -
                    id: 4
                    name: 項威
                    group: APP
                    created_at: '2023-08-21T04:04:35.000000Z'
                    updated_at: '2023-08-21T04:04:35.000000Z'
                    tasks:
                      -
                        id: 12
                        task_descr: 'Itaque aut repellat rerum nemo aut necessitatibus. Praesentium ut voluptatem excepturi quae voluptatem aliquid consequatur.'
                        member_id: '4'
                        creator_id: '10'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 21
                        task_descr: 'Aut in itaque quia cum facere. Quidem sit omnis voluptas animi quia. Similique voluptatem assumenda facilis occaecati.'
                        member_id: '4'
                        creator_id: '5'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 43
                        task_descr: 'Fugit delectus dolorum ut sunt. Voluptates nesciunt voluptatem doloribus minima et aliquam. Laboriosam laborum enim id harum. Enim adipisci quam unde rerum.'
                        member_id: '4'
                        creator_id: '12'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                  -
                    id: 5
                    name: 巴文依
                    group: APP
                    created_at: '2023-08-21T04:04:35.000000Z'
                    updated_at: '2023-08-21T04:04:35.000000Z'
                    tasks:
                      -
                        id: 15
                        task_descr: 'Et est sit sed dolores amet quasi cupiditate. Architecto provident in culpa occaecati aliquam. Ut sint dolore quo beatae maiores nostrum facere.'
                        member_id: '5'
                        creator_id: '1'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 18
                        task_descr: 'Neque velit asperiores sint tempora deserunt. Eaque ut autem et eos in maxime sint. Fuga nulla omnis dolorum voluptatibus magni temporibus beatae ut. Ut quo aspernatur quis mollitia soluta aut quia.'
                        member_id: '5'
                        creator_id: '3'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 23
                        task_descr: 'Aliquam quisquam deserunt culpa sit quae nemo. Quos reprehenderit aut eos dicta dolor aut.'
                        member_id: '5'
                        creator_id: '9'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 41
                        task_descr: 'Rerum et dolorem eaque. Ut sunt sunt modi quaerat assumenda.'
                        member_id: '5'
                        creator_id: '11'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                  -
                    id: 6
                    name: 喬哲華
                    group: UI/UX
                    created_at: '2023-08-21T04:04:35.000000Z'
                    updated_at: '2023-08-21T04:04:35.000000Z'
                    tasks:
                      -
                        id: 4
                        task_descr: 'Qui fugiat quo repellendus ut. Similique voluptatem fugit quis ut. Soluta ea eos unde itaque autem quia.'
                        member_id: '6'
                        creator_id: '8'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 6
                        task_descr: 'Mollitia inventore minima architecto est ratione. Repellendus eius nostrum quo sit consequatur aut et. Ad ipsum aut qui ducimus iusto aliquam et. Necessitatibus sint aliquam natus adipisci.'
                        member_id: '6'
                        creator_id: '4'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 26
                        task_descr: 'Ad qui fugiat reiciendis enim dolores beatae. Vel laudantium dolorum quia necessitatibus. Sed est deserunt et ab. Placeat error quas harum deleniti aliquid aut corrupti.'
                        member_id: '6'
                        creator_id: '8'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                  -
                    id: 7
                    name: 武文華
                    group: Front-end
                    created_at: '2023-08-21T04:04:35.000000Z'
                    updated_at: '2023-08-21T04:04:35.000000Z'
                    tasks:
                      -
                        id: 19
                        task_descr: 'Ducimus quam tempore qui sed omnis distinctio facilis itaque. Fuga quo incidunt reiciendis consequatur nihil ut. Qui ad distinctio ut omnis.'
                        member_id: '7'
                        creator_id: '7'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 32
                        task_descr: 'Recusandae odit molestiae sequi veniam in omnis consequatur. Rerum soluta reiciendis fugiat consequatur. Velit velit sed quia aspernatur et illo sequi.'
                        member_id: '7'
                        creator_id: '11'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                      -
                        id: 40
                        task_descr: 'Est aliquam tenetur labore harum placeat molestias. Culpa tenetur consectetur accusamus ut explicabo quae est. Reprehenderit fugiat dolor magni nesciunt qui eligendi.'
                        member_id: '7'
                        creator_id: '10'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                      -
                        id: 44
                        task_descr: 'Quas nemo nisi odit repudiandae. Quo sunt laboriosam aliquam vitae aut sunt. Voluptatem consequatur in temporibus et dolor quo excepturi quibusdam. Harum minima non omnis similique.'
                        member_id: '7'
                        creator_id: '9'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                  -
                    id: 8
                    name: 卜銘柏
                    group: UI/UX
                    created_at: '2023-08-21T04:04:35.000000Z'
                    updated_at: '2023-08-21T04:04:35.000000Z'
                    tasks:
                      -
                        id: 11
                        task_descr: 'Impedit nemo assumenda quis sit. Pariatur similique optio aut eos commodi eaque at aspernatur. Nisi perspiciatis quo quia laboriosam rerum et. Architecto cupiditate ut eum pariatur maiores.'
                        member_id: '8'
                        creator_id: '11'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 17
                        task_descr: 'Nihil suscipit soluta id dolor rerum non nihil. Quod corrupti autem sit eum necessitatibus inventore est. Eum totam expedita et rem quasi voluptatem dolorem.'
                        member_id: '8'
                        creator_id: '3'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 49
                        task_descr: 'Deserunt provident voluptas et qui. Omnis deserunt suscipit vitae autem exercitationem dolorum expedita architecto. Ea minus consequatur dolorem quia quo voluptatum. Qui qui saepe sit quos velit.'
                        member_id: '8'
                        creator_id: '4'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                  -
                    id: 9
                    name: 公孫思宗
                    group: APP
                    created_at: '2023-08-21T04:04:35.000000Z'
                    updated_at: '2023-08-21T04:04:35.000000Z'
                    tasks:
                      -
                        id: 1
                        task_descr: 'buy coffee'
                        member_id: '9'
                        creator_id: '9'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 06:15:20'
                      -
                        id: 2
                        task_descr: 'Est sunt et culpa velit voluptas magnam. Adipisci tempora ad dolorum et qui. Et est similique quam. Alias quia quae quia nam dolorem placeat. Dolorem provident error et totam cum ut.'
                        member_id: '9'
                        creator_id: '2'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 3
                        task_descr: 'Nihil assumenda voluptatem quas officiis unde officiis est. Sunt vero quae non enim possimus esse. Magnam animi inventore nulla dicta accusantium perspiciatis.'
                        member_id: '9'
                        creator_id: '7'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 22
                        task_descr: 'Enim dolores excepturi aut voluptatem accusantium optio magnam. Earum nisi ea officiis cupiditate aut velit quo.'
                        member_id: '9'
                        creator_id: '3'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 24
                        task_descr: 'Dolorem error voluptas assumenda quia. Asperiores a amet quaerat qui reprehenderit doloremque. Autem consequuntur natus minus repudiandae. Architecto deserunt unde et nesciunt.'
                        member_id: '9'
                        creator_id: '11'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 27
                        task_descr: 'Error qui atque dolores libero ea minus ut. Inventore dignissimos dolorem sequi et. Perspiciatis ut harum amet incidunt aut quia maxime.'
                        member_id: '9'
                        creator_id: '10'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 29
                        task_descr: 'Et fugiat natus rerum recusandae. Corporis voluptatum distinctio et. Odit ipsa ut ut cum incidunt. Vitae in quia reiciendis et saepe qui explicabo.'
                        member_id: '9'
                        creator_id: '11'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 31
                        task_descr: 'Quam cumque porro autem explicabo dolore. A blanditiis pariatur facere ut vel debitis iure. Officia est omnis est et nihil reiciendis ratione. Culpa cum ipsum voluptas aliquid saepe.'
                        member_id: '9'
                        creator_id: '6'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                      -
                        id: 34
                        task_descr: 'Fugiat dolor autem illo dolorem. Temporibus aut fugit in est odio dolore quisquam. Vel ipsa odio et voluptas a repudiandae sit. Tempore eum in maxime quibusdam dolor corporis id.'
                        member_id: '9'
                        creator_id: '2'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                      -
                        id: 39
                        task_descr: 'Voluptas aut magnam velit libero corrupti. Labore et laudantium tempora sit laudantium et. Eum et quaerat quis vel.'
                        member_id: '9'
                        creator_id: '5'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                      -
                        id: 46
                        task_descr: 'Quasi veritatis et nostrum numquam. Velit quia tempore minus eaque. Id incidunt consequatur distinctio enim. Tenetur minima dolor non laboriosam repellat et.'
                        member_id: '9'
                        creator_id: '3'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                  -
                    id: 10
                    name: 鄂琬
                    group: Front-end
                    created_at: '2023-08-21T04:04:35.000000Z'
                    updated_at: '2023-08-21T04:04:35.000000Z'
                    tasks:
                      -
                        id: 14
                        task_descr: 'Delectus aliquid alias quo beatae sit. Dolor ratione asperiores animi magnam. Sint dolores quidem itaque nihil.'
                        member_id: '10'
                        creator_id: '5'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 30
                        task_descr: 'Non fugit quae dignissimos tempore. Dolorum quia iste modi enim accusamus ratione aperiam. Voluptatem magni vitae et ex saepe. Exercitationem dolor quod veniam qui sit sint quia cumque.'
                        member_id: '10'
                        creator_id: '3'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                  -
                    id: 11
                    name: 燕霖樺
                    group: APP
                    created_at: '2023-08-21T04:04:35.000000Z'
                    updated_at: '2023-08-21T04:04:35.000000Z'
                    tasks:
                      -
                        id: 10
                        task_descr: 'Repellat voluptatem blanditiis tempore maiores et. Ipsum fuga rerum culpa aut. Voluptatum et tempora dolorum voluptas. Ut quo omnis perferendis nobis consequatur provident id.'
                        member_id: '11'
                        creator_id: '1'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 13
                        task_descr: 'Earum fugiat nobis rerum voluptas sapiente nulla omnis. Aut dolorem ducimus quia veniam.'
                        member_id: '11'
                        creator_id: '9'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 36
                        task_descr: 'Fugiat est occaecati maiores quod amet omnis temporibus rem. Laudantium animi sunt molestiae rerum ab. Corrupti hic consectetur velit quisquam sit et.'
                        member_id: '11'
                        creator_id: '6'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                      -
                        id: 45
                        task_descr: 'Et consequatur sint quia doloribus vel adipisci. Sit aut nihil unde. Voluptatem et nisi expedita soluta vel tempore vel. Dicta minima quia aut enim.'
                        member_id: '11'
                        creator_id: '10'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
                  -
                    id: 12
                    name: 苗淑
                    group: Back-end
                    created_at: '2023-08-21T04:04:35.000000Z'
                    updated_at: '2023-08-21T04:04:35.000000Z'
                    tasks:
                      -
                        id: 7
                        task_descr: 'Non voluptate suscipit aut aut provident ab quia. Velit id ullam harum voluptas corporis odit.'
                        member_id: '12'
                        creator_id: '10'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 9
                        task_descr: 'Et cupiditate velit odio vel qui officiis. Pariatur consequuntur fugiat impedit ullam aut architecto dicta. Qui aspernatur voluptate enim quia illo.'
                        member_id: '12'
                        creator_id: '4'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 20
                        task_descr: 'Accusamus numquam iusto omnis quaerat quasi voluptatem commodi. Sint debitis ut fuga et. Exercitationem aut provident consectetur expedita et. Quos tempore esse sint tenetur consectetur sit atque.'
                        member_id: '12'
                        creator_id: '3'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 28
                        task_descr: 'Sed nihil nihil dolores vel aut minus consequatur. Ut laboriosam et reiciendis modi voluptate harum ut. Occaecati quia ut quasi rerum quo.'
                        member_id: '12'
                        creator_id: '11'
                        created_at: '2023-08-21 04:04:34'
                        updated_at: '2023-08-21 04:04:34'
                      -
                        id: 33
                        task_descr: 'Explicabo illo iusto dolores aperiam ut quis ut. Quod sunt odio nihil aliquid aut ut.'
                        member_id: '12'
                        creator_id: '4'
                        created_at: '2023-08-21 04:04:35'
                        updated_at: '2023-08-21 04:04:35'
      tags:
        - 'Member 成員資料'
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - 'data saved'
      tags:
        - 'Member 成員資料'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'value 不能超過 255 個字元.'
                  example: dmemdwvmcheqszjvuxmhw
                group:
                  type: string
                  description: 'value 不能超過 255 個字元.'
                  example: wixkzriupnozeyocjoiujktez
              required:
                - name
                - group
  '/api/member/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  name: 帥依庭
                  group: UI/UX
                  created_at: '2023-08-21T04:04:35.000000Z'
                  updated_at: '2023-08-21T04:04:35.000000Z'
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: 帥依庭
                  group:
                    type: string
                    example: UI/UX
                  created_at:
                    type: string
                    example: '2023-08-21T04:04:35.000000Z'
                  updated_at:
                    type: string
                    example: '2023-08-21T04:04:35.000000Z'
      tags:
        - 'Member 成員資料'
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  name: 帥依庭
                  group: UI/UX
                  created_at: '2023-08-21T04:04:35.000000Z'
                  updated_at: '2023-08-21T04:04:35.000000Z'
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: 帥依庭
                  group:
                    type: string
                    example: UI/UX
                  created_at:
                    type: string
                    example: '2023-08-21T04:04:35.000000Z'
                  updated_at:
                    type: string
                    example: '2023-08-21T04:04:35.000000Z'
      tags:
        - 'Member 成員資料'
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        204:
          description: ''
      tags:
        - 'Member 成員資料'
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the member.'
        example: 1
        required: true
        schema:
          type: integer
  /api/task:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters:
        -
          in: query
          name: sort
          description: sort
          example: 'asc / desc'
          required: true
          schema:
            type: string
            description: sort
            example: 'asc / desc'
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  Status: error
                  Message: 'invalid input of sort'
                properties:
                  Status:
                    type: string
                    example: error
                  Message:
                    type: string
                    example: 'invalid input of sort'
      tags:
        - 'Task 任務資料'
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  Status: success
                  Message: 'data saved'
                properties:
                  Status:
                    type: string
                    example: success
                  Message:
                    type: string
                    example: 'data saved'
      tags:
        - 'Task 任務資料'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task_descr:
                  type: string
                  description: 'value 不能超過 255 個字元.'
                  example: rmbezdgehjlsldq
                member_id:
                  type: integer
                  description: 'value 不能大於 255.'
                  example: 5
              required:
                - task_descr
                - member_id
  '/api/task/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    task_descr: 'buy coffee'
                    member_id: '9'
                    member_name: 公孫思宗
                    member_group: APP
                    creator_id: '9'
                    created_at: '2023-08-21 12:04:34'
                    updated_at: '2023-08-21 14:15:20'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      task_descr:
                        type: string
                        example: 'buy coffee'
                      member_id:
                        type: string
                        example: '9'
                      member_name:
                        type: string
                        example: 公孫思宗
                      member_group:
                        type: string
                        example: APP
                      creator_id:
                        type: string
                        example: '9'
                      created_at:
                        type: string
                        example: '2023-08-21 12:04:34'
                      updated_at:
                        type: string
                        example: '2023-08-21 14:15:20'
      tags:
        - 'Task 任務資料'
    put:
      summary: ''
      operationId: putApiTaskId
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    task_descr: reprehenderit
                    member_id: '9'
                    member_name: 公孫思宗
                    member_group: APP
                    creator_id: '9'
                    created_at: '2023-08-21 12:04:34'
                    updated_at: '2023-08-22 10:26:59'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      task_descr:
                        type: string
                        example: reprehenderit
                      member_id:
                        type: string
                        example: '9'
                      member_name:
                        type: string
                        example: 公孫思宗
                      member_group:
                        type: string
                        example: APP
                      creator_id:
                        type: string
                        example: '9'
                      created_at:
                        type: string
                        example: '2023-08-21 12:04:34'
                      updated_at:
                        type: string
                        example: '2023-08-22 10:26:59'
      tags:
        - 'Task 任務資料'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task_descr:
                  type: string
                  description: 'The context of the task description.'
                  example: reprehenderit
                member_id:
                  type: integer
                  description: 'The id of the member who is asign to the task.'
                  example: 9
                creator_id:
                  type: integer
                  description: 'The id of the user who creat the task.'
                  example: 9
              required:
                - task_descr
                - member_id
                - creator_id
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  Status: success
                  Message: 刪除成功
                properties:
                  Status:
                    type: string
                    example: success
                  Message:
                    type: string
                    example: 刪除成功
      tags:
        - 'Task 任務資料'
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the task.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
  -
    name: 'Member 成員資料'
    description: ''
  -
    name: 'Task 任務資料'
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
